name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install dependencies
        run: |
          python -m pip install -U build
      - name: build wheel
        run: |
          python -m build --wheel
          rm dist/index.js* || true
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: publish package distributions to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
